### ISSUE TITLE
Playground Applications Sources can't be updated - jscrambler-webpack-plugin

### ISSUE THREAD

**Issue by achmadk** [jscrambler/jscrambler#113]
Hello, Jscrambler team. Thanks for provide `jscrambler-webpack-plugin`, its an awesome library.

I am trying to use `jscrambler-webpack-plugin` into my project. I have registered into jscrambler account then fill `applicationId`, `accessKey` and `secretKey`, but I got this error when building my project.

```
Update application sources failed with Error: Playground Applications Sources can't be updated
Failed to compile.

Error: Playground Applications Sources can't be updated
```

is there any option to fix this error?

**Comment by joaosamouco** [comment]
Hello @achmadk :wave: Thank you for reaching out to us.

It seems like you are using the `applicationId` of your Playground application. That application is intended to be used as a demo/playground where you can try different transformations and templates.

If you want to upload your own source files you should create a new application on [Jscrambler Dashboard](https://app.jscrambler.com) and use that application `applicationId` on your `jscrambler-webpack-plugin` configuration.
