### ISSUE TITLE
Error 401 Unauthorized - Invalid signature, When obfuscating

### ISSUE THREAD

**Issue by gangadharuseline** [jscrambler/jscrambler#117]
Hi Team,

We are using jscrambler obfuscator as part of our react-native application build process.

The client we are using jscrambler-metro-plugin
Version: 5.5.27

When we are running the react-native bundle command,
We are getting the below error
```
info Writing bundle output to:, ./ios/myapp/main.jsbundle
info Done writing bundle output
info Copying 416 asset files
info Done copying assets
info Jscrambler Obfuscating Code
Error: Unexpected Response: 401 Unauthorized - Invalid signature. Make sure that you are using valid access keys and are running the most recent version of the Jscrambler client
    at new ClientError (/Users/gangadhar/myapp/node_modules/jscrambler/dist/client.js:65:112)
    at /Users/gangadhar/myapp/node_modules/jscrambler/dist/client.js:297:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  statusCode: 401
}
error Command failed with exit code 1.
```

Then I tried updating the metro plugin to latest version
"jscrambler-metro-plugin": "^6.2.0",

Then When we are running the react-native bundle command,
We are getting the below error
```
info Writing bundle output to:, ./ios/myapp/main.jsbundle
info Done writing bundle output
info Copying 416 asset files
info Done copying assets
info Jscrambler Obfuscating Code
Global protection errors:
- Entry point was provided but could not find any matching AST

Error: Protection failed. For more information visit: https://app.jscrambler.com.
    at _callee3$ (/Users/gangadhar/myapp/node_modules/jscrambler/dist/index.js:644:33)
    at tryCatch (/Users/gangadhar/myapp/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/gangadhar/myapp/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/gangadhar/my_app/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/gangadhar/myapp/node_modules/jscrambler/dist/index.js:66:103)
    at _next (/Users/gangadhar/Documents/myapp/node_modules/jscrambler/dist/index.js:68:194)
    at /Users/gangadhar/Documents/myapp/node_modules/jscrambler/dist/index.js:68:364
    at new Promise (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can anyone please help me.

**Comment by luiscubal** [comment]
Hello,

can you give me a few more details regarding this ticket?

  * Do you have a file named `.jscramblerignore` in your project?
  * What is your jscrambler account? If you don't want to share the email address here (in a public ticket), you can also send it to support@jscrambler.com.

Thank you.

**Comment by luiscubal** [comment]
Typically, this is caused by the `.jscramblerignore` file having a line with `node_modules`. This is unnecessary because our metro plugin already ignores `node_modules`.

Remove the `node_modules` line from the `.jscramblerignore` file and it should work again.

**Comment by gangadharuseline** [comment]
Thank you so much @luiscubal 
Yeah It's working after I removed node_modules from the . jscramblerignore file
obfuscation is successfully done.
(jscrambler-metro-plugin: 6.2.0
