### ISSUE TITLE
Bug: The API fails if the `filesSrc` contains only a single file 

### ISSUE THREAD

**Issue by skilledDeveloper** [jscrambler/jscrambler#124]
`options.filesSrc` accepts an array of strings but if you pass a single filename like the following it will fail:
```
options.filesSrc = ["file1.js"]
```

The problem is not with the obfuscation process. It happens after that when it tried to write the file in the output directory:
```
 Error: EISDIR: illegal operation on a directory, open 'OUTOUT_DIR'
```

Workaround: Adding another file in the `filesSrc` will fix the issue.

**Comment by luisreis-jscr** [comment]
Hello. The issue here is that when the project has only a single file, Jscrambler outputs a file instead of outputting a directory.

Is this causing you problems?

**Comment by luisreis-jscr** [comment]
There is a way to turn off this behavior: if you make the `filesDest` field end in a "/" or "\\", it will always output a folder, even if only one single file was protected.

Example: `options.filesDest = "dist/";`
