### ISSUE TITLE
jscrambler-webpack-plugin accept config file path

### ISSUE THREAD

**Issue by oreporan** [jscrambler/jscrambler#137]
Currently the `JscramblerWebpack` plugin does not accept the path of a config file, can we add it?

**Comment by f-ribeiro** [comment]
Hello,

Currently you can import that file and pass the configuration to our Webpack Plugin, as such:


```
const JscramblerWebpack = require('jscrambler-webpack-plugin');
const jscramblerConfig = require(PATH_TO_CONFIG_FILE);

plugins: {
  new JscramblerWebpack({
    ...jscramblerConfig
  })
}
```

Does this solve your issue?

**Comment by luiscubal** [comment]
Closing due to there being a workaround and the issue being inactive.

If the specified workaround is not useful, feel free to open a new issue explaining the problem you are facing.
