### ISSUE TITLE
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported

### ISSUE THREAD

**Issue by dartess** [jscrambler/jscrambler#198]
Hey hey! Hope you are doing well.
Please update the `glob` dependency, as currently installing `jscrambler@8.6.0` causes a warning in the console.
Thank you in advance!

**Comment by f-ribeiro** [comment]
Hello @dartess , thank you for the heads up!

It shall be fixed after [this PR](https://github.com/jscrambler/jscrambler/pull/199) is accepted and a new version released.
