### ISSUE TITLE
Fatal error: [Error: Error: The application you are trying to protect does not have any file to protect]

### ISSUE THREAD

**Issue by errolgr** [jscrambler/jscrambler#22]
For those that are experience the issue below 

> Fatal error: [Error: Error: The application you are trying to protect does not have any file to protect]

I think jscrambler updated their API in the back end to reject any file extension wildcards, all of a sudden jscrambler was not detecting any of the javscript files in my project.

In order to fix the issue I had to change my general wildcard from 

`
	files: [{
				    expand:true,
					src: ['www/app/**/*', 'www/app/*'],
					dest: 'www/'
				}]
`

to

`
	files: [{
				    expand:true,
					src: ['www/app/**/*.js', 'www/app/*.js'],
					dest: 'www/'
				}]
`

Hope this helps somebody!

**Comment by magano** [comment]
Just tried with both approaches and they worked as intended.
Can you please provide more information so we can try to reproduce the issue on our side?

**Comment by magano** [comment]
Alright, that is indeed an issue, we've just opened an issue and will address it as soon as possible.

We'll keep you informed on the status of the issue.

**Comment by joaosamouco** [comment]
@errolgr a new client version was released and this issue should be solved. Please get back to us if the problem still persists.

**Comment by rmribeirojs** [comment]
The fix worked for me.
