### ISSUE TITLE
Unsupported jscramber version and 400 error (CLI)

### ISSUE THREAD

**Issue by vv001** [jscrambler/jscrambler#33]
Hi,

After running the CLI command to scramble a JS file, through:
"jscrambler -c jscrambler.json -o temp-scramble testfile.js"

I kept getting the following error:
Request failed with status code 400

After that I reinstalled Jscramber with version 5.2.18 (latest) and now keep getting the following error:
Unexpected Response: 400 Unsupported Jscrambler Version

Right now I am kind of stuck on why this is happening, since the command used to work normally.
Any help is appreciated. Thanks in advance.

**Comment by joaosamouco** [comment]
Hi @vv001,

That error occurs when you are trying to use a deprecated Jscrambler version. Currently available versions are 5.4, 5.5 (stable) and 5.6 (lastest).

You are probably specifying an old version on your jscrambler.json file. Can you check the jscramblerVersion value on that file?

**Comment by vv001** [comment]
That did the trick. Thanks!

**Comment by anishg-cn** [comment]
i am getting this error and it is not solved even after writing the correct version number in .jscramblerrc file. Please help.

**Comment by anishg-cn** [comment]
@joaosamouco but the jscrambler version that is install from npm is of version 6.1.1?

**Comment by f-ribeiro** [comment]
Hi @anishg-cn ,
We have just added a [new page to our Docs](https://docs.jscrambler.com/7.2/code-integrity/documentation/jscrambler-configuration-file) with info regarding the Jscrambler Configuration File.
Let me know if that helped.
