### ISSUE TITLE
Required *applicationId* not provided

### ISSUE THREAD

**Issue by vzaidman** [jscrambler/jscrambler#34]
our config:
```
{
  "applicationId": "00c8f01e1a3b00011234f005", // i changed it a little to paste here
  "params": [
    ///// paramas
  ],
  "areSubscribersOrdered": false,
  "applicationTypes": {
    "webBrowserApp": true,
    "desktopApp": false,
    "serverApp": false,
    "hybridMobileApp": false,
    "javascriptNativeApp": false,
    "html5GameApp": false
  },
  "languageSpecifications": {
    "es5": true,
    "es6": false,
    "es7": false
  },
  "useRecommendedOrder": false,
  "jscramblerVersion": "5.5"
}
```
the command we use
```
jscrambler --werror -c ../../jscrambler.json -o ./ ./dist/production/index.js \
           -s ${JSCRAMBLER_SECRET_KEY} -a ${JSCRAMBLER_ACCESS_KEY}
```
the config file is resolved for sure. i changed the path and i had an error that it didn't.

**Comment by joaosamouco** [comment]
Hi @vzaidman,

It looks like there is an issue when setting the `--werror` flag in that way and we will fix it in an upcoming release. For now, you can bypass that problem by using the following command:

```bash
jscrambler --werror true -c ../../jscrambler.json -o ./ ./dist/production/index.js \
           -s ${JSCRAMBLER_SECRET_KEY} -a ${JSCRAMBLER_ACCESS_KEY}
```

**Comment by vzaidman** [comment]
thanks! it works :)

**Comment by MebDevelop** [comment]
Well, I have integrated Jscrambler to my react-native project and I am getting this issue while releasing apk in Android Studio. Do you have any idea about this?

**Comment by joaosamouco** [comment]
> Well, I have integrated Jscrambler to my react-native project and I am getting this issue while releasing apk in Android Studio. Do you have any idea about this?

This error indicates that you are not providing the required `applicationId` parameter in your jscrambler configuration. You can check where to grab your `applicationId` [here](https://docs.jscrambler.com/code-integrity/documentation/api/clients). Are you using any of our clients?

You can find more information on integrating Jscrambler with React Native [on our documentation](https://docs.jscrambler.com/code-integrity/frameworks-and-libraries/react-native).

**Comment by MebDevelop** [comment]
Thank you for your really quick message.
I followed the documentation. I download the config file from the jscrambler site and paste it as .jscramblerrc

**Comment by joaosamouco** [comment]
> Thank you for your really quick message.
> I followed the documentation. I download the config file from the jscrambler site and paste it as .jscramblerrc. And in there I can see the project id as well

Do you mind contacting our support team at support@jscrambler.com?

**Comment by MebDevelop** [comment]
I sent email to them

**Comment by stephaniegoldman12** [comment]
This is happening to me as well (same error message appID not provided). Followed these steps: https://blog.jscrambler.com/protecting-your-react-js-source-code-with-jscrambler/. Am I missing something?
