### ISSUE TITLE
5.2.2 - Source map file name has the extension ".js" in its middle portion.

### ISSUE THREAD

**Issue by phcoliveira** [jscrambler/jscrambler#4]
The source map file returned together with the protected file is not named properly. Here it is an example:

**jscrambler-demo.js-c56d97b247d70ba34f2f5d147f0ad3b9.map**

I believe the `.js` were not meant to be put after the application name, in the middle portion of the file name.

**Comment by magano** [comment]
Hello,
We are already addressing this and we should come up with a fix soon.
Sorry for the inconvenience.

Best Regards,
Vítor Magano
