### ISSUE TITLE
Don't require babel-polyfill

### ISSUE THREAD

**Issue by benoneal** [jscrambler/jscrambler#43]
Line 7 of `jscrambler/dist/index.js` is `require('babel-polyfill');`. 

This prevents use of the programmatic API within any ES6 module-compatible application. Any attempt to import the jscrambler library, and then run with `babel-node` or similar, will result in the following error: 

`Error: only one instance of babel-polyfill is allowed`

There's no reason for the exported module to include this polyfill as a dependency, as the module should have been transpiled as an ES5 compatible commonjs module. 

Right now this is blocking our ability to integrate this tool into our dynamic asset pipeline. 

Steps to reproduce: 
```js
// test.js
import jscrambler from 'jscrambler'
```
```sh
$ npx babel-node test.js
/Users/xxx/node_modules/babel-polyfill/lib/index.js:10
  throw new Error("only one instance of babel-polyfill is allowed");
  ^

Error: only one instance of babel-polyfill is allowed
```

**Comment by gualterandre** [comment]
Hello Ben

We apologize but this got lost on our backlog since this issue section is not handled by Jscrambler Support.
If this is still an issue I will kindly ask you to send an email to:

support@jscrambler.com

So that our Engineering Team can take a look at this.

Best regards

Gualter
