### ISSUE TITLE
[RN] Error calling protectAndDownload from metro-plugin

### ISSUE THREAD

**Issue by kryjex** [jscrambler/jscrambler#46]
I have noticed that config.filesDest -which is sent in protectAndDownload- needs an "/" at the end, otherwise it returns the EISDIR error.

The constant is originally concatenated in this line:
https://github.com/jscrambler/jscrambler/blob/84628d1fff332b91671a84cc0817eab3deb2b2d0/packages/jscrambler-metro-plugin/lib/index.js#L9

To then be used in this other line:
https://github.com/jscrambler/jscrambler/blob/e051e48c6965e12e84e57414d49301e4296bc7b5/packages/jscrambler-cli/src/index.js#L389

I see that beyond simply changing the line inside jscrambler-metro-plugin, there may be a bug in the next block of code, although I'm not sure if it affects other parts of the monorepo.
https://github.com/jscrambler/jscrambler/blob/7d770913e3a1315f7ae52c3382c5757392abf4ce/packages/jscrambler-cli/src/zip.js#L135-L145

**Comment by joaosamouco** [comment]
Thank you for reporting the issue and spending the time to fix it. We found out that the issue was just present in some environments and that's why we couldn't notice it earlier. It has been merged and will be released in the next version of `jscrambler-metro-plugin`.
