### ISSUE TITLE
Error: You have exceeded the number of files in your application

### ISSUE THREAD

**Issue by HyunmoAhn** [jscrambler/jscrambler#59]
I have a below error when build using `jscrambler-webpack-plugin`.

It used to be successful, but from some point on, the build is failing with a message.

Can you tell which is the cause?

```
Error: You have exceeded the number of files in your application
    at /Users/user/project/tw-bank-webapp/node_modules/jscrambler/dist/index.js:72:13
```

**Comment by gualterandre** [comment]
Hello

This may be related to your subscription/account.

To report issues on our products please use our support email at:

support@jscrambler.com

Thanks!

**Comment by HyunmoAhn** [comment]
Ok I request to mail. Once the issue is closed, I'll comment on the reason when

**Comment by HyunmoAhn** [comment]
It was lisence issue. If you have occur same issue, You need to report support team.
