### ISSUE TITLE
Running Tests? (Javascript library)

### ISSUE THREAD

**Issue by CodeMan99** [jscrambler/jscrambler#8]
**REPEAT OF** jscrambler/javascript-jscrambler#26 :-1: Why were no issues handled upon deprecating the previous repository?

--

I'm unsure how the test suite is suppose to function. I'd like to improve the test coverage for a pull request I am preparing, but when I run `npm test` this is the output I get:

```
> jscrambler@5.2.1 test /home/code_m/dev/jscrambler/packages/jscrambler-cli
> grunt test 2> /dev/null

>> Local Npm module "grunt-babel" not found. Is it installed?

Running "clean:test" (clean) task
>> 0 paths cleaned.

Running "jasmine_node:test" (jasmine_node) task


Finished in 0.001 seconds
0 tests, 0 assertions, 0 failures, 0 skipped




Running "clean:test" (clean) task
>> 0 paths cleaned.

Done.
```

**Comment by antonio-jscrambler** [comment]
Hi, 

We are sorry that we didn't handle the issues on the deprecated repo and thank you for creating the issue again.

Regarding the tests for the javascript client, they are aimed to check some use cases like upload, download, get info, protection, etc. 

At the moment the `npm test` command isn't running as intended. We will investigate the issue and address it soon.

We would like to thank you for your effort and help to improve the clients.

**Comment by s-coimbra21** [comment]
Hi, this probably not what you wanted to hear but those tests are for an old version of our CLI, I have just removed them to prevent any further confusion about it.

That said, feel free to submit any PR you wish, we will review it in due time.

**Comment by CodeMan99** [comment]
Oh man. The changes I want to contribute are large and sweeping changes. Scary to submit code you've never ran.
