### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by michael-s-gibson** [jscrambler/jscrambler#85]
Hi,

I have to use the JScrambler CLI through a corporate proxy (only supplying a host and port) and the latest version (5.5.18) does not look like it works with proxies; I keep getting an `ETIMEDOUT` error.

On looking at [client.js](https://github.com/jscrambler/jscrambler/blob/master/packages/jscrambler-cli/src/client.js), I see it's using HttpsProxyAgent rather than Axios (lines 199-200).

```
settings.proxy = false;
settings.httpsAgent = new HttpsProxyAgent({host, port, auth: formattedAuth, ...agentOptions});
```

If I change the above lines to use the proxy object
```
settings.proxy = {host, port}
//settings.httpsAgent = new HttpsProxyAgent({host, port, auth: formattedAuth, ...agentOptions});
``` 
or roll back to a version before the HttpProxyAgent commits (5.5.8 for example), the proxy works.

Is there a reason why HttpsProxyAgent is not working?

**Comment by gualterandre** [comment]
Hello

We need to investigate this with our Engineering Team. Can you please send this issue directly to:

support@jscrambler.com

So our Team can take a look at this?

Thanks
