### ISSUE TITLE
Ember-CLI-Jscrambler does not work properly with Ember@2.16.2

### ISSUE THREAD

**Issue by phcoliveira** [jscrambler/jscrambler#9]
Hello again!

We got the whole set to work perfectly when using `ember@2.12.3`:

-  `ember-cli-deploy-lightning-pack`
-  `ember-cli-jscrambler`
-  `ember-cli-bugsnag`

Bugsnag were able to trace errors correctly from either ES5 **and** ES6 source maps. The trick for getting ES6 source maps it to have this option inside `ember-cli-build.js`:

```
babel: {
  sourceMaps: 'inline'
}
```

From `ember@2.13.0` onwards, this option is ignored and we don't expect to see ES6 source maps from these newer builds.

Nevertheless, we do expect to see ES5 source maps in all versions, particularly `ember@2.16.2`. I have just confirmed that, when `ember-cli-jscrambler` is removed from the dependencies, Bugsnag is able to trace to the development files transpiled to ES5. That is acceptable and we do not have a problem with that.

But when `ember-cli-jscrambler` is added again, Bugsnag can't do anything with the final source map provided by you. It points the errors back to the protected file.

I suppose something in its code is not ready for the module renaming presented in `ember@2.16.2`, things like `from "@ember/object"`. Or it could be something else regarding how an addon may plug itself to this newer version.

This is a working distribution folder by `ember@2.16.2`, built without `ember-cli-jscrambler`:
[deploy-dist.zip](https://github.com/jscrambler/jscrambler/files/1662007/deploy-dist.zip)

And this one was built with `ember-cli-jscrambler`, still `ember@2.16.2`, which has a source map that Bugsnag cannot use:
[deploy-dist-with-jscrambler.zip](https://github.com/jscrambler/jscrambler/files/1662035/deploy-dist-with-jscrambler.zip)

**Comment by phcoliveira** [comment]
Answering a request from Jorge, here it is our file `ember-cli-build.js`
``` Javascript
/* eslint-env node */
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // NOTE: The original, concatenated, transpilled application
    // files are only used for Jscrambler to produce the protected
    // ones. Therefore, there is no need to minify them.
    // Jscrambler has a setting for minifying the protected
    // application files.
    minifyJS: {
      options: {
        exclude: ['**/jscrambler-demo.js']
      }
    },

    // NOTE: By default, source maps are disabled for production.
    // They must be enabled in production in order to Jscrambler
    // get them and return new source maps for the protected files.
    sourcemaps: {
      enabled: true,
      extensions: ['js']
    },

    // NOTE: This can be removed, but bear in mind that protecting
    // libraries like JQuery and Ember might have a big impact on
    // general performance.
    // 'ember-cli-jscrambler': {
    //   exclude: ['**/vendor.js'],
    // },

    // NOTE: This option, which use to enable source maps pointing to the
    // original development files, written in ES6, in version "2.12.3",
    // is ignored since Ember-CLI "2.13.X".
    // There is not much to read about it, with the core team admitting
    // to have lost track of the root of this issue. Please see the links bellow:
    //
    // https://github.com/ember-cli/ember-cli/issues/6066#issuecomment-302550292
    // https://github.com/ef4/fast-sourcemap-concat/issues/39
    // babel: {
    //   sourceMaps: 'both'
    // }
  });

  return app.toTree();
};
```

**Comment by antonio-jscrambler** [comment]
This issue was handled by the support team. Will close it now. Thanks for the feedback.
