### ISSUE TITLE
Error: Unexpected Response: socket hang up

### ISSUE THREAD

**Issue by trunggeo** [jscrambler/jscrambler#95]
Hi,

I have used jscrambler-cli and received error as bellow:
```
Error: Unexpected Response: socket hang up
    at new ClientError (/Users/trung/Projects/node_modules/jscrambler/dist/client.js:65:112)
    at /Users/trung/Projects/node_modules/jscrambler/dist/client.js:297:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 500
}
```
I try to go deeper and it seems like relate to the issue about:
```
{
    statusCode: 403,
    error: 403,
    message: 'Application Profiling is not available in your plan.'
  }
```
I have tried to reinstall/update jscrambler, nodejs... but it still does not work
Is there any way to resolve this issue?

**Comment by gualterandre** [comment]
Hello

We need to further investigate this issue.

Can you please send an email to:

support@jscrambler.com

So that our engineering team can take a look at this?

Thanks

Gualter

**Comment by trunggeo** [comment]
Turns out the issue is on my antivirus filter.
It works fine when I turn it off and change the connection.

I will close this issue.
Thank you for your support.
